### PR TITLE
rwd & general improvements

### PR DESCRIPTION
**Pull request by AnmolS1**
In the previous pull, the design looked pretty bad on phone screens:
before
I've modified the css by making it responsive such that it looks like this on phone screens:
after

I also added in remote event updates. Rather than directly editing the HTML file, which can cause issues regarding time and effort, I created a text file wherein each event is a line of the format "name : date : description". This will make it far easier to update the events regularly.

### CODE REVIEW

**Comment by michl1001** [comment]
Found some issues on my end?
Part of it is I tweaked the styling a bit and they conflict with the changes

**Comment by AnmolS1** [comment]
I've fixed the conflicting issues. Everything should be smooth now.

**Comment by michl1001** [comment]
Noice! Looks good, we should probably 
A) get the about section to be responsive as well
B) set a minimum size where the page goes static

**Comment by michl1001** [comment]
Also currently fixing some styling for the about and navbar rn, will finish soon

**Comment by michl1001** [comment]
Current issues left: 
- need a phone view for about section
- navbar logo a text get misplaced on sizes < 400px wide
- need to set a minimum size for site(event card get screwed up a really small sizes)

**Comment by AnmolS1** [comment]
I can work on those tonight. I'll commit when done.

**Comment by AnmolS1** [comment]
Fixed all issues mentioned

&check; created phone view for about section
&check; fixed navbar logo and text misplacement
&check; set a minimum size for site

**Comment by michl1001** [comment]
Holy heck!! This looks good! Sorry about the late response - was setting up some background logistics for webmaster. LGTM

**Review by michl1001 — APPROVED** [review]

**Pull request merged**
